version: '3.8'

services:
  mongodb1:
    image: mongo:latest
    container_name: mongodb1
    ports:
      - "27017:27017"
    volumes:
      - mongodb1_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: "database1"
  
  mongodb2:
    image: mongo:latest
    container_name: mongodb2
    ports:
      - "27018:27017"
    volumes:
      - mongodb2_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: "database2"

volumes:
  mongodb1_data:
  mongodb2_data:
